version: '3.4'

services:

  category_service:
    container_name: category_service
    image: category_service
    build:
      context: ./CategoryApp
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - "Env=qa"

  ticket_service:
    container_name: ticket_service
    image: ticket_service
    build:
      context: ./TicketApp
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      - "Env=qa"
    depends_on:
      - rabbitmq

  user_service:
    container_name: user_service
    image: user_service
    build:
      context: ./UserApp
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    environment:
      - "Env=qa"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqConf:/rabbitmqConf